### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by maltewhiite** [devfile-samples/devfile-sample-python-basic#10]
Please add a readme for this. I am having trouble getting it working in openshift gui

**Comment by eaespinosa** [comment]
Please add a readme for this. I am having trouble getting it working in openshift gui

**Comment by michael-valdron** [comment]
Closing this issue due to its age, if this is still an issue please feel free to open another issue on [devfile/api](https://github.com/devfile/api/issues/new/choose) with the details of your request :slightly_smiling_face: 

FYI @maltewhiite
