### ISSUE TITLE
DevFile doesn't running in Red Hat OpenShift Dev Spaces 3.10.1 provided by Red Hat

### ISSUE THREAD

**Issue by adelahozredhat** [devfile-samples/devfile-sample-python-basic#41]
This repository doesn't running in openshift 4.14 or crc2.31.0
DevSpace operator version
Red Hat OpenShift Dev Spaces
3.10.1 provided by Red Hat

![image](https://github.com/devfile-samples/devfile-sample-python-basic/assets/95278768/d59de97e-0d23-4d08-a7e2-ae15f2381740)

**Comment by thepetk** [comment]
Hey @adelahozredhat could you also share any logs related to this issue?

**Comment by thepetk** [comment]
> nothing on the openshift sorry. only timeout

@adelahozredhat 

From my side I've tried to reproduce. I was able to reproduce a timeout error but the workspace build failed on the "waiting the editor to start" step. AFAIK this means that all k8s components were created successfully (I was able to confirm that through the openshift console).

More detailed I've tried to create a che workspace in devspaces by importing the https://github.com/devfile-samples/devfile-sample-python-basic repo

Could you share what you see in the "progress" tab?

**Comment by michael-valdron** [comment]
See my comment: https://github.com/devfile/api/issues/1423#issuecomment-2008008201

If this issue persists it should be tracked and re-opened on devfile/api#1423.
